[package]
name = "json_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.81"
rand = "0.8.5"
serde = { version = "1.0.29", features = ["derive"] }
redis = "0.21.5"
