sharding:
  clusterRole: configsvr
replication:
  replSetName: ConfigServerSet
net:
  bindIp: config-server-3
  port: 27017
storage:
  dbPath: /home/mongo/dbc3
systemLog:
  destination: file
  path: /home/mongo/dbc3/dbc3.log
processManagement:
  pidFilePath: /home/mongo/dbc3/dbc3.pid
