sharding:
  clusterRole: configsvr
replication:
  replSetName: ConfigServerSet
net:
  bindIp: config-server-2
  port: 27017
storage:
  dbPath: /home/mongo/dbc2
systemLog:
  destination: file
  path: /home/mongo/dbc2/dbc2.log
processManagement:
  pidFilePath: /home/mongo/dbc2/dbc2.pid
